scss_files: "css/**/*.css"

preprocess_command: "sed '1{/^---$/!q;};1,/^---$/d'"

exclude:
  - "css/_fonts.css"
  - "css/_highlight.css"

linters:
  Comment:
    enabled: false

  HexLength:
    enabled: true
    style: short

  HexNotation:
    enabled: true
    style: uppercase

  ImportPath:
    enabled: false

  LeadingZero:
    enabled: true
    style: include_zero

  NestingDepth:
    enabled: true
    max_depth: 5
    ignore_parent_selectors: false

  PropertySortOrder:
    enabled: true
    order:
      - position
      - top
      - right
      - bottom
      - left
      - background
      - background-size
      - color
      - width
      - height
      - margin
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - border
      - border-color
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-radius
      - font
      - font-size
      - font-weight
      - font-style
      - line-height
      - letter-spacing
      - text-align
      - text-decoration
      - text-transform
      - display
      - float
      - opacity

  SelectorDepth:
    enaledd: true
    max_depth: 5

  SingleLinePerSelector:
    enabled: true

  StringQuotes:
    enabled: true
    style: double_quotes
