sudo: false
cache: bundler
language: ruby

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

rvm:
  - 2.2.3

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --check-html true --log-level debug --url-ignore "/^https?://localhost/","/cloud\.digitalocean\.com/","/\?refcode\=/","/r\/3edceb992aa254/","/https://dribbble\.com/account/applications/","/^https?://example\.local/"
