sudo: false
cache: bundler
language: ruby

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

rvm:
  - 2.1.5
  - 2.2.0

script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --check-html true --href-ignore "/^https?://localhost/","/cloud\.digitalocean\.com/","/\?refcode\=/","/r\/3edceb992aa254/" --verbose
