defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "article"

exclude:
  - Gemfile
  - Gemfile.lock
  - config
  - vendor

permalink: "/:year/:month/:day/:title/"

sass:
    sass_dir: _includes/stylesheets
    style: compressed

url: "http://localhost:4000"
