assets:
  caching:
    path: ".jekyll-assets-cache"
    type: file
    enabled: true
  compression: true
  sources:
    - "_assets/javascripts"
    - "_assets/stylesheets"

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "article"

exclude:
  - Gemfile
  - Gemfile.lock
  - config
  - vendor

markdown: kramdown

permalink: "/:year/:month/:day/:title/"

url: "http://localhost:4000"
