assets:
  cache: true
  autosize: true
  js_compressor: uglifier
  css_compressor: sass

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "article"

exclude:
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Procfile
  - config
  - vendor

markdown: kramdown

permalink: "/:year/:month/:day/:title/"
