assets:
  cache: .jekyll-assets-cache
  compress:
    js: true
    css: true
  features:
    automatic_img_alt: false

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "article"

exclude:
  - Capfile
  - Gemfile
  - Gemfile.lock
  - config
  - vendor

markdown: kramdown

permalink: "/:year/:month/:day/:title/"

url: "http://localhost:4000"
