defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

description: "I'm a developer, remote worker, and a hockey fan living in Boston."

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Procfile.dev
  - config.ru
  - css/_*.css
  - lib
  - node_modules
  - package.json
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - yarn.lock

kramdown:
  syntax_highlighter: "rouge"
  syntax_highlighter_opts:
    formatter: "CustomHighlighter"

permalink: "/journal/:title/"

plugins:
  - jekyll-postcss
  - jekyll-redirect-from

redirect_from:
  json: false

url: "http://localhost:4000"
