name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Determine the Ruby version
        id: ruby-version
        run: echo "RUBY_VERSION=$(cat .ruby-version)" >> $GITHUB_ENV
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Determine the Node version
        id: node-version
        run: echo "NODE_VERSION=$(cat package.json | perl -pe '($_)=/"node":\s+"([0-9]+([.][0-9]+)+)"/')" >> $GITHUB_ENV
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - name: Install the Node dependencies
        run: yarn install
      - name: Lint the code
        run: |
          bundle exec rubocop
          bundle exec scss-lint
          yarn lint
      - name: Build and verify the website
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build
          bundle exec htmlproofer ./_site --no-check-external-hash --checks Images,Links,OpenGraph,Scripts --log-level debug --ignore-urls "/^https?://localhost/","/^https?://example\.local/","/r\/3edceb992aa254/","/https://dribbble\.com/account/applications/","/https://angel\.co/u/tristan-dunn/","/^https://twitter\.com/","/^https://(www\.)?instagram\.com/","/^https://docs\.github\.com/","/^https://cloud\.digitalocean\.com/"
      - name: Scan for vulnerabilities
        run: |
          bundle exec bundler-audit
