name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Determine the Ruby version
        id: ruby-version
        run: echo "::set-output name=version::$(cat .ruby-version)"
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.version }}
          bundler-cache: true
      - name: Determine the Node version
        id: node-version
        run: |
          echo "::set-output name=version::$(cat package.json | perl -pe '($_)=/"node":\s+"([0-9]+([.][0-9]+)+)"/')"
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: "yarn"
      - name: Install the Node dependencies
        run: yarn install --pure-lockfile
      - name: Lint the code
        run: |
          bundle exec rubocop
          bundle exec scss-lint
          yarn lint
      - name: Build and verify the website
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build
          bundle exec htmlproofer ./_site --checks Images,Links,OpenGraph,Scripts --log-level debug --ignore-urls "/^https?://localhost/","/^https?://example\.local/","/r\/3edceb992aa254/","/https://dribbble\.com/account/applications/","/https://angel\.co/u/tristan-dunn/","/^https://twitter\.com/","/^https://(www\.)?instagram\.com/"
      - name: Scan for vulnerabilities
        run: |
          bundle exec bundler-audit
