name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: Cache the Ruby dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundle-
      - name: Install the Ruby dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Determine the Node version
        id: node-version
        run: |
          echo "::set-output name=version::$(cat package.json | perl -pe '($_)=/"node":\s+"([0-9]+([.][0-9]+)+)"/')"
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node-version.outputs.version }}
      - name: Find the Yarn cache directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache the Node dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install the Node dependencies
        run: yarn install --pure-lockfile
      - name: Lint the code
        run: |
          bundle exec rubocop
          bundle exec scss-lint
          yarn lint
      - name: Build and verify the website
        run: |
          bundle exec jekyll build
          bundle exec htmlproofer ./_site --check_html true --check_opengraph true --log-level debug --url-ignore "/^https?://localhost/","/^https?://example\.local/","/r\/3edceb992aa254/","/https://dribbble\.com/account/applications/","/https://angel\.co/u/tristan-dunn/"
      - name: Scan for vulnerabilities
        run: |
          bundle exec bundler-audit
